[St-301] Optimized database code structure.
SeredaYehor/FaceSpam_social_media pull request #60
Opened 2022-06-05 13:53 UTC by maximdrozdov

2022-06-05 14:12 UTC, SeredaYehor requested changes
Code has been reviewed. Now try to optimize it for dev branch

2022-06-05 14:57 UTC, SeredaYehor requested changes
Reviewed files

2022-06-07 12:59 UTC, SeredaYehor commented
![image](https://user-images.githubusercontent.com/74448293/172385816-8c8fccee-8ca0-4abb-b3c5-f16e1870152d.png)

2022-06-07 13:04 UTC, SeredaYehor commented
Возникло несколько багов. Первый из них это повторяющиеся кнопки в окне друзей. Второй баг связан с js скриптом на главной странице, после отправки сообщения оно не отображается на странице, ещё есть проблема с главными страницами друзей. Если перейти на страницу друга, то под его аватаркой будет кнопка подружиться. Последняя проблема возникла со страницей сообщений, ибо там работает только селект чата, но сообщение не отправляються и не выводяться. А так всё хорошо.

2022-06-07 17:12 UTC, Fur1mo commented
> Возникло несколько багов. Первый из них это повторяющиеся кнопки в окне друзей. Второй баг связан с js скриптом на главной странице, после отправки сообщения оно не отображается на странице, ещё есть проблема с главными страницами друзей. Если перейти на страницу друга, то под его аватаркой будет кнопка подружиться. Последняя проблема возникла со страницей сообщений, ибо там работает только селект чата, но сообщение не отправляються и не выводяться. А так всё хорошо.

Да, я знаю. Я просто закинул обновления в гит, что бы не потерять. Сейчас буду продолжать писать код 0-0

2022-06-09 20:34 UTC, closed without merging